In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image_dataset_from_directory

In [2]:
dataset = image_dataset_from_directory('./test/', label_mode='binary')

Found 11 files belonging to 2 classes.


2021-10-11 10:40:51.042076: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-11 10:40:51.045590: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-11 10:40:51.045789: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-11 10:40:51.046173: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [3]:
dataset.take(1)

<TakeDataset shapes: ((None, 256, 256, 3), (None, 1)), types: (tf.float32, tf.float32)>

In [4]:
plt.figure(figsize=(10, 10))
for images, labels in dataset.take(1):
    print(labels)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(11, 1), dtype=float32)


2021-10-11 10:40:51.450137: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


<Figure size 720x720 with 0 Axes>

In [5]:
dataset = image_dataset_from_directory('./test/', label_mode='categorical')

Found 11 files belonging to 2 classes.


In [6]:
plt.figure(figsize=(10, 10))
for images, labels in dataset.take(1):
    print(labels)

tf.Tensor(
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]], shape=(11, 2), dtype=float32)


<Figure size 720x720 with 0 Axes>

In [7]:
dataset = image_dataset_from_directory('./test/', label_mode='int')

Found 11 files belonging to 2 classes.


In [8]:
plt.figure(figsize=(10, 10))
for images, labels in dataset.take(1):
    print(labels)

tf.Tensor([1 1 1 1 0 1 0 0 0 1 0], shape=(11,), dtype=int32)


<Figure size 720x720 with 0 Axes>